on:
  push:
    paths:
      - "eAIP/**"
    branches:
      - main
name: Deploy eAIP to Krystal FTP
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 141.98.26.4
          username: ${{ secrets.EAIP_FTP_USER }}
          password: ${{ secrets.EAIP_FTP_PWD }}
          local-dir: "eAIP/"
          state-name: ".ftp-deploy-sync-state-overview.json"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
